/**
 * Generates src/components/ToolIcons.tsx.
 *
 * Brand marks come from the simple-icons package so they are the real
 * trademarks rather than approximations. Microsoft does not license its
 * product marks through that set, so Power BI, Power Query and the generic
 * concepts (SQL, ERP) use purpose-drawn glyphs on the same 24x24 grid —
 * which is fine, because at this size and in one colour a drawn glyph reads
 * more consistently than a mismatched official mark would.
 *
 * Run:  node scripts/gen-icons.mjs
 */
import { writeFileSync } from 'node:fs'
import * as si from 'simple-icons'

const byTitle = {}
for (const icon of Object.values(si)) {
  if (icon && icon.title) byTitle[icon.title] = icon
}

const brand = {
  python: 'Python',
  mysql: 'MySQL',
  gsheets: 'Google Sheets',
  gmaps: 'Google Maps',
  appsscript: 'Google Apps Script',
  js: 'JavaScript',
}

// Purpose-drawn, 24x24, filled — same visual weight as the brand marks.
const drawn = {
  powerbi: 'M3.2 20.8V9.6h4.2v11.2H3.2zm7.2 0V3.2h4.2v17.6h-4.2zm7.2 0v-7.4h4.2v7.4h-4.2z',
  powerquery: 'M2.6 3.6h18.8l-7.2 8.6v6.9l-4.4 2.3v-9.2L2.6 3.6z',
  sql:
    'M12 2.4c4.5 0 8.1 1.2 8.1 2.7S16.5 7.8 12 7.8 3.9 6.6 3.9 5.1 7.5 2.4 12 2.4z' +
    'M3.9 8.1c1.7 1 4.6 1.6 8.1 1.6s6.4-.6 8.1-1.6v3.3c0 1.5-3.6 2.7-8.1 2.7s-8.1-1.2-8.1-2.7V8.1z' +
    'M3.9 14.4c1.7 1 4.6 1.6 8.1 1.6s6.4-.6 8.1-1.6v3.3c0 1.5-3.6 2.7-8.1 2.7s-8.1-1.2-8.1-2.7v-3.3z',
  erp: 'M3 3h7.4v7.4H3V3zm10.6 0H21v7.4h-7.4V3zM3 13.6h7.4V21H3v-7.4zm10.6 0H21V21h-7.4v-7.4z',
}

const entries = []
for (const [key, title] of Object.entries(brand)) {
  const icon = byTitle[title]
  if (!icon) throw new Error(`simple-icons is missing "${title}"`)
  entries.push([key, icon.path])
}
for (const [key, path] of Object.entries(drawn)) entries.push([key, path])

const body = entries
  .map(([key, path]) => `  ${key}:\n    '${path}',`)
  .join('\n')

const file = `/* AUTOGENERATED by scripts/gen-icons.mjs — do not edit by hand.
   Re-run \`node scripts/gen-icons.mjs\` after changing that script. */

export const ICON_PATHS: Record<string, string> = {
${body}
}

/** Maps the strings used in data/projects.ts \`stack\` to an icon key. */
export const STACK_ICONS: Record<string, string> = {
  'Power BI': 'powerbi',
  'Power Query': 'powerquery',
  DAX: 'powerbi',
  SQL: 'sql',
  MySQL: 'mysql',
  'ERP data': 'erp',
  'ERP integration': 'erp',
  'ERP Systems': 'erp',
  Python: 'python',
  'Apps Script': 'appsscript',
  'Google Apps Script': 'appsscript',
  JavaScript: 'js',
  'Google Maps API': 'gmaps',
  'Google Sheets': 'gsheets',
}
`

writeFileSync(new URL('../src/components/ToolIcons.ts', import.meta.url), file)
console.log(`wrote ${entries.length} icons`)
